# Train/val/test sets
train: '\\wsl.localhost\Ubuntu\home\victor\machine_learning\computed_vision\detection\yolo\yolov8\detection_faces\images\train'
val: '\\wsl.localhost\Ubuntu\home\victor\machine_learning\computed_vision\detection\yolo\yolov8\detection_faces\images\validation'
test: '\\wsl.localhost\Ubuntu\home\victor\machine_learning\computed_vision\detection\yolo\yolov8\detection_faces\images\test'

# Classes
names:
  0: face